### ISSUE TITLE
Pixel artifacts

### ISSUE THREAD

**Issue by reddured** [hongyuanyu/SPAN#9]
Thank you for this great model which performs very quickly. I notice a significant issue that could be related to rgb_mean and img_range values. When using your pretrained model spanx4_ch48.pth, upscaled image almost always contain pixel artifacts that make final picture unusable (see image) :

![image](https://github.com/user-attachments/assets/fe3e263b-b0e2-4066-8ff5-96ad346c5858)

How can I solve this problem ? Thanks.

**Comment by ZHAOZHIHAO** [comment]
When I use their codes, I normalize the image as in their codes but don't do de-normalization, but clip the output to [0, 1]. By doing so, the output looks good to me.
